### ISSUE TITLE
Problem understanding how to use the component

### ISSUE THREAD

**Issue by nltesown** [flekschas/svelte-simple-modal#16]
Hi,

I've been looking at your example, and the REPL (https://svelte.dev/repl/033e824fad0a4e34907666e7196caec4?version=3.20.1), but something is not clear for me in the structure `<Modal><Content /></Modal>`. At first, I thought that `<Content />` would simply be the content of the modal, but it seems that `<Modal>` is a wrapper for the whole app.

For instance, in the REPL, it seems very weird to me that the links to open the various exemples ("popup", "popup with long text", etc.), and the logic to control them, are all located within this top-level `<Modal>`.

Sorry if I don't sound very clear, but I don't know where to start to put a modal in my existing project. I would expect to add the `<Modal>` component beside the rest of my elements/components, not _around_ them.

**Comment by flekschas** [comment]
I am sorry the structure isn't clear. Let me try to clarify.

> it seems that <Modal> is a wrapper for the whole app.

This is correct. `<Modal>` needs to wrap your entire app or just the part of the app in which you want to call/trigger the modal, in order to expose the modal context.

> I would expect to add the <Modal> component beside the rest of my elements/components, not around them.

No, you have to wrap the component with `<Modal>` in which you want to trigger/call/open a modal. The reason why is because simple-modal exposes a _context_ that provides the `open()` method to open a modal, i.e., `const { open } = getContext('simple-modal');`. This context is _only_ available for child components of `<Modal>`.

Imagine your component tree looks like this:

- App
  - Header
  - Main
     - Headline
     - Text
     - ...
  - Footer

And you want to show a modal that superimposes _Main_ when being open. To do so you'd have to wrap _Main_ as follows:

- App
  - Header
  - **Modal**
     - Main
         - Headline
         - Text
         - ...
  - Footer

Now any component below _Modal_ (e.g., Main, Headline, Text, ...) can open a modal (using `const { open } = getContext('simple-modal');`) that will superimpose _Main_.

If you want to show a modal that superimposes the entire application then you'd have to wrap _App_ instead.

Does this help to clarify the structure?

**Comment by nltesown** [comment]
Yes, thanks a lot for your answer, it is much clearer for me now.

**Comment by spsaucier-bakkt** [comment]
This was very helpful, thanks. The error I was getting when assuming `<Modal>` was a wrapper for modal content only was a `500: TypeError: Cannot destructure property `open` of 'undefined' or 'null'.`
