### ISSUE TITLE
Alternative to context API?

### ISSUE THREAD

**Issue by samdoeswork** [flekschas/svelte-simple-modal#22]
Hi, is it possible to expose an alternative to the context API (a store or prop or similar) ?

The reason is - as I understand it the context API forces a structure like this
`
<Modal>
   <ModalWrapper>
        <ModalContent>
   </ModalWrapper>
</Modal>`

So if you want to invoke the component from App.svelte, the context is undefined. So App.svelte can never directly open the Modal - if my understanding is correct.

This seems restrictive just to obtain a reference - but I'm no Svelte expert so I could be wrong.

Thanks for your work on this

**Comment by flekschas** [comment]
> API forces a structure like this
The structure is a follows: `<App><Modal><ComponentA>...<BComponentB></App></Modal>`

> So if you want to invoke the component from App.svelte, the context is undefined. So App.svelte can never directly open the Modal - if my understanding is correct.
It depends on where in the component tree your `App.svelte` is located. Any component above the modal won't be able to use it's context, that's how context work.

Practically I don't think this is a problem, you just need to move logic into a component below Modal.

One benefit is that the child components don't need to think about the Modal instantiation or anything. E.g., imagine this setup:

```
<App>
  <ModalA>
    <ComponentA>
      <ComponentA1 />
    </ComponentA>
  </ModalA>
  <ModalB>
    <ComponentB>
      <ComponentB1 />
    </ComponentA>
  </ModalB>
</App>
```

We can have two modals (e.g., a left and right modal in a two-column layout) but neither `<ComponentA1 />` nor `<ComponentB1 />` need to know which modal they are triggering. We could even swap and everything would work as expected. Even if we would wrap `<ComponentB />` with yet another component, the modal would work as before.

**Why not a store?**

I am not aware of a much more elegant way to use stores. The `<Modal />` could depend on a store being passed in as a prop (e.g., `<Modal show={} />`) but then the out application needs to model the modal's state correctly. To test how this would look like I've created https://svelte.dev/repl/f0d828b6ca2e4b08a00fadabbba67f29?version=3.20.1 which depends on a store now. I am not sure I find this better because the developer needs to remember what the store format should be e.g.: `{ component, props, options, callbacks }` (See `ContentNew.svelte`). It's not a huge burden but I also don't see a clear benefit that this new setup would bring.

Having said that, there's a more elegant way I am not against replacing the current context approach.

**Comment by davemccrea** [comment]
Would it be feasible to use both the store and context APIs? As @flekschas suggests, it would be possible to pass in a store as a prop, then call both `store.set({ open, close }})` and `setContext(key, { open, close })`. Or, perhaps it makes more sense to do:

```javascript
<script>
    export let store;
    
    if (store) {
        store.set({ open, close });
    } else {
        setContext(key, { open, close });
    }
</script>
```

Either way, there are no breaking changes.

I agree with @samdoeswork that it would be useful to programatically open/close the modal from outside the <Modal /> component. As an example, I am showing a product overview using a fullscreen modal on smaller screens. In testing, some users (read: my wife) expected the back button to close the modal (given that it looks and feels like a page change). Using stores would make this trivial.

**Comment by flekschas** [comment]
I am not sure the motivation is clear to me. If you're using the modal to overlay your complete app, why not add the modal to the root of your component tree?

Regarding your concrete proposal, I have three comments:
1. I would always expose the context. There's no reason not to expose the context API or am I missing something?

2. How would we handle non-writable stores and `<Modal />` that is conditionally invoked?

3. Having the modal set a store during run time means that whoever is relying on the store needs to check whether `<Modal />` was already initialized. This isn't particularly challenging but it does add the potential for hiccup. For instance, in an outer component one would have to do something like this:
   ```html
   <script>
   import { modal } from './stores.js';
   function clickHandler() {
     if (modal.open) modal.open(...)
     else console.warn('Modal does not seem to have been initialized yet. Too bad');
   }
   </script>
   <button on:click={clickHandler}>Open Modal</button>
   ```
   The benefit is that we know if the modal is available or not. The downside is what should happen if it's not? Or if the `<Modal />` is invoked conditionally? This is not an issue if we rely on a prop (e.g. `<Modal show={modal} />` where `modal` is a store holding the modal component and props).

Again, I am not against it, I am just want to make sure the API remains simple and solid.

**Comment by flekschas** [comment]
Here's my proposal for an alternative to the context API: I'll add a component prop called `show` to `<Modal />` that accepts a Svelte component.

Here's a super simple static example:

```svelte
<script>
  import SomethingElse from './SomethingElse.svelte';
  import Modal from './Modal.svelte';
  import Popup from './Popup.svelte';
</script>

<Modal show={Popup}>
  <SomethingElse />
</Modal>
```

Of course you can also pass in a store

```svelte
<!-- App.svelte -->
<script>
  import { writable } from 'svelte/store';
  import Content from './Content.svelte';
  import Popup from './Popup.svelte';
  export const modal = writable(null);

  function showModal() {
    modal.set(Popup)
  }
</script>

<Content />
<button on:click={showModal}>Show modal</button>


<!-- Content.svelte -->
<script>
  import Modal from 'svelte-simple-modal';
  import SomethingElse from './SomethingElse.svelte';
  import { modal } from './App.svelte';
</script>

<Modal show={$modal}>
  <SomethingElse />
</Modal>
```

A live example can be found at https://svelte.dev/repl/f0d828b6ca2e4b08a00fadabbba67f29?version=3.20.1

Since it was not obvious to me how to pre-bind props to a component, I've added a helper function that achieves this.

```svelte
<script>
  import { bind } from 'svelte-simple-modal';
  import Popup from './Popup.svelte';
  import { modal } from './App.svelte';

  modal.set(bind(Popup, { name: 'custom name' }));
</script>
```

Let me know what you think.

**Comment by Androz2091** [comment]
Yes, it's a good idea
