### ISSUE TITLE
Cannot focus select with tabulation using a select library

### ISSUE THREAD

**Issue by brian-dechoux** [flekschas/svelte-simple-modal#49]
Hello, I am trying to use this modal library along with another library, [Svelte-Select](https://github.com/rob-balfre/svelte-select).

When I use a Select in the opened modal, I'm not able to get focus on the select. I also cannot continue to tabulate through other inputs afterward.

I created a REPL with my exact versions:
https://svelte.dev/repl/7423b7a7c40c4e0e90cf40c919739d59?version=3.12.1

In the modal, click on the first input, and try to access others using only tabulation.

Any thoughts on what could be the cause of this issue ?

**Comment by brian-dechoux** [comment]
I found what's causing the issue. If I remove the custom keydown 'Tab' handler, I have the expected behaviour.  
What's the purpose of this handler in the first place ?

**Comment by flekschas** [comment]
Thanks for reporting the issue and finding the source. We added the keydown tab handler to _trap_ the focus insight the Modal following the [WAI-ARIA guidelines](https://www.w3.org/TR/wai-aria-practices/#dialog_modal): https://github.com/flekschas/svelte-simple-modal/issues/17.

Playing around with the code a bit it turns out the issue is caused by how svelte-select handles focused elements: https://svelte.dev/repl/09b4ec466c03475e8a5b9ab6e1eca3d0?version=3.12.1

1. When you tab once, the close button is focused
2. When you tab twice, the first input is focused
3. When you tab three times, the svelte-select should be focused but somehow it delegates the focus state to the body
4. When you tab four times, you'd expect that the third input gets focused but the issue is that `document.body` isn't contained within the modal, hence, the focus cycle starts from the beginning again and you're going to focus on the close button.

I am not sure there's a way for svelte-simple-modal to handle this special case. My only idea is that you could google to figure out if svelte-select can stop it's focus delegation. Or we could add an option to not trap the focus in the modal but that can lead to unwanted side effects.

**Comment by brian-dechoux** [comment]
Thanks for your investigation.  
I will look deeper on how focus is handled in svelte-select, and try to find a way around the problem, preferably without making the trap feature an option.

**Comment by flekschas** [comment]
Did you find a solution to your problem? If so, would you mind posting it? Others might run into the same problem at some point :)

**Comment by brian-dechoux** [comment]
I did not find a suitable solution for now, but I will be posting it for sure if I find something

**Comment by flekschas** [comment]
After seeing that not even Material UI can fully ensure that trapping the focus works in all cases, I suggest implementing a similar solution that allows disabling the focus track.

https://mui.com/components/modal/#focus-trap

@brian-dechoux What do you think?

**Comment by brian-dechoux** [comment]
I agree on a prop enabling/disabling the focus track.  
I know this is a compromise to the detriment of accessibility, but in my case the application is not used for a large audience so we know exactly all the users.

**Comment by flekschas** [comment]
@brian-dechoux Can you give https://svelte.dev/repl/5e4a4f868fe346c382f9f86c8d706470?version=3.44.1 a test?
The focus should be trapped within the modal for all modals except when you open the dialog ("Show a dialog").

You can enable disabling either when creating the Modal (e.g., `<Modal disableFocusTrap={true}>`) or via a custom option when you call `open()` (e.g., `open(ModalComponent, modalComponentProps, { disableFocusTrap: true });`)

Let me know what you think and if it works.

**Comment by brian-dechoux** [comment]
In my case, I always use the second way to open a modal so perfect !  
Also, I tried the dialog with the svelte-dropdown using the same version I used in my REPL, and it works by disabling the focus trap.
