### ISSUE TITLE
Draggable style for modal?

### ISSUE THREAD

**Issue by bitdom8** [flekschas/svelte-simple-modal#51]
Thx for great component. Can we implement draggable modal dialogs?

**Comment by flekschas** [comment]
Thank you for your suggestion but I am not planning to make the modal draggable. While it might be interesting and useful in some cases, this could lead to all kind of UX issues and might require some level of complexity that is outside the scope of this package. I can of course be convinced otherwise if you have some background information / material for the use case and how you'd go about implementing it.
