### ISSUE TITLE
Add typescript definitions

### ISSUE THREAD

**Issue by auderer** [flekschas/svelte-simple-modal#52]
It would be great to have typescript definitions for the props on this component.

**Comment by flekschas** [comment]
That would indeed be great and I am happy to merge a PR. Do you want to take a stab at fleshing out the type definitions?

**Comment by flekschas** [comment]
I took a stab at it and generated type definitions with sveld. However, before I merge the change I'd like to ask you if you can give it a try by installing the following version. Are the types picked up as expected?

### Install Instruction
1. Download [svelte-simple-modal-1.0.4.tgz.zip](https://github.com/flekschas/svelte-simple-modal/files/7493131/svelte-simple-modal-1.0.4.tgz.zip)
1. Unzip the package
  (I had to zip the tarball because GitHub does not allow uploads of `.tgz` files. However, `.zip` are allowed 🤷‍♂️)
2. Go to a local repo that uses svelte-simple-modal
3. Install the npm tarball: `npm install path/to/the/downloaded/tarball/svelte-simple-modal-1.0.4.tgz`

The `<Modal />` should work as expected but you should have type annotations for all exports.

**Comment by flekschas** [comment]
Addressed via #1b5bcd4 and published in v1.1.1.
